-- Reformulação dos segmentos econômicos de clientes
DELETE FROM client_segments;

INSERT INTO client_segments (name, category, is_active, sort_order) VALUES
('Agronegócio', 'Segmentos', true, 10),
('Bares e Restaurantes', 'Segmentos', true, 20),
('Beleza e Estética', 'Segmentos', true, 30),
('Combustíveis', 'Segmentos', true, 40),
('Comércio', 'Segmentos', true, 50),
('Construção Civil', 'Segmentos', true, 60),
('Educação', 'Segmentos', true, 70),
('Energia', 'Segmentos', true, 80),
('Entretenimento', 'Segmentos', true, 90),
('Eventos', 'Segmentos', true, 100),
('Finanças', 'Segmentos', true, 110),
('Holding e Participações', 'Segmentos', true, 120),
('Hotelaria', 'Segmentos', true, 130),
('Imobiliário', 'Segmentos', true, 140),
('Indústria', 'Segmentos', true, 150),
('Locação de bens', 'Segmentos', true, 160),
('Logística', 'Segmentos', true, 170),
('Marketing e Publicidade', 'Segmentos', true, 180),
('Mineração', 'Segmentos', true, 190),
('ONG', 'Segmentos', true, 200),
('Petróleo e Gás', 'Segmentos', true, 210),
('Rádio e TV', 'Segmentos', true, 220),
('Reciclagem', 'Segmentos', true, 230),
('Saneamento Básico', 'Segmentos', true, 240),
('Saúde', 'Segmentos', true, 250),
('Seguros', 'Segmentos', true, 260),
('Serviço Profissional', 'Segmentos', true, 270),
('Setor Público', 'Segmentos', true, 280),
('Silvicultura', 'Segmentos', true, 290),
('Tecnologia', 'Segmentos', true, 300),
('Transporte', 'Segmentos', true, 310),
('Turismo', 'Segmentos', true, 320),
('Outros', 'Segmentos', true, 330);
